### ISSUE TITLE
网络重建精确率为0

### ISSUE THREAD

**Issue by xingye1999** [ShawXh/RNCE#1]
我利用1000M样本对Arxiv GR-QC数据集进行RNCE方法训练，网络重构精确率为0，请问这需要训练多少个样本？

**Comment by ShawXh** [comment]
你跑的应该是原始数据集吧？我这两天上传一份洗过的数据

**Comment by xingye1999** [comment]
好的，感谢

**Comment by ShawXh** [comment]
我上传数据了，gr-qc的数据比较小，应该跑50M个采样轮次就够了

**Comment by xingye1999** [comment]
感谢，已经差不多可以正常复现了。
